# Generated by Django 3.0.5 on 2022-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('cv_data', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
